<?php

use Illuminate\Database\Seeder;

use App\SubGenre;
use Carbon\Carbon;

class SubGenresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // UTC時間
        $dt = Carbon::now()->format('Y-m-d H:i:s');
        SubGenre::insert([
            ['genre_id' => 9585, 'title' => "歯科", 'param' => 65, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9585, 'title' => "矯正歯科", 'param' => 9646, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9585, 'title' => "小児歯科", 'param' => 9644, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9585, 'title' => "歯科口腔外科", 'param' => 9645, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9585, 'title' => "デンタルドック", 'param' => 9647, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 3, 'title' => "内科", 'param' => 70, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "眼科", 'param' => 62, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "整形外科", 'param' => 9621, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "耳鼻咽喉科", 'param' => 66, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "皮膚科", 'param' => 72, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "小児科", 'param' => 67, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "産婦人科", 'param' => 64, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "診療所・療養所", 'param' => 74, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "外科", 'param' => 60, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "精神科", 'param' => 69, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "アレルギー科", 'param' => 9624, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "胃腸消化器科", 'param' => 9625, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "気管食道外科", 'param' => 9630, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "休日・夜間診療機関", 'param' => 75, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "休日夜間医療", 'param' => 75, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "形成外科", 'param' => 9622, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "肛門科", 'param' => 9459, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "呼吸器科", 'param' => 9635, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "循環器科", 'param' => 9632, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "小児科系", 'param' => 67, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "小児外科", 'param' => 9620, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "助産師・助産所", 'param' => 9640, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "神経内科", 'param' => 9612, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "心臓血管外科", 'param' => 9616, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "心療内科", 'param' => 9613, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "性感染症科", 'param' => 9642, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "総合病院", 'param' => 76, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "乳腺外科", 'param' => 9618, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "人間ドック", 'param' => 68, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "脳神経外科", 'param' => 9615, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "泌尿器科", 'param' => 71, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "美容外科", 'param' => 9623, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "婦人科", 'param' => 9641, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "放射線科", 'param' => 77, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "ホスピス・緩和ケア", 'param' => 9610, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "麻酔科", 'param' => 9643, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "リウマチ科", 'param' => 717, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "リハビリテーション", 'param' => 9614, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 3, 'title' => "リハビリテーション科", 'param' => 9450, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 5, 'title' => "美容院", 'param' => 1028, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "宝石・時計・貴金属", 'param' => 96, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "貸衣裳", 'param' => 101, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "エステ・サロン", 'param' => 1022, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "洋服・仕立て直し", 'param' => 1015, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "床屋・理容店・散髪", 'param' => 1030, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "レディース・婦人服", 'param' => 1036, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "靴・履物・修理", 'param' => 1016, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "衣料品・子供服", 'param' => 100, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "かさ・修理", 'param' => 5249, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "かばん・バック・修理", 'param' => 1059, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "化粧品・コスメ", 'param' => 1900113, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "制服・作業服", 'param' => 104, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ボディペイント", 'param' => 1900112, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "メンズ・紳士服", 'param' => 1034, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "毛髪業", 'param' => 1050, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ランジェリー", 'param' => 5001, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "和服", 'param' => 105, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "水道", 'param' => 1900153, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "税理士", 'param' => 1979, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "弁護士", 'param' => 1990, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "司法書士", 'param' => 1972, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "リサイクルショップ", 'param' => 119, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "質屋", 'param' => 1971, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "タクシー", 'param' => 225, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "写真・スタジオ", 'param' => 224, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "家具修理・雑貨修理", 'param' => 5244, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ごみ収集・資源回収", 'param' => 217, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "インターネット", 'param' => 1900147, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "占い・手相", 'param' => 143, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "運転代行", 'param' => 5326, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "家政婦紹介", 'param' => 1923, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "行政書士", 'param' => 1966, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "銀行・郵貯", 'param' => 1891, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "空港・飛行機・ヘリ", 'param' => 4350, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "クリーニング・コインランドリー", 'param' => 215, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "携帯・スマホ", 'param' => 2014, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ごみ処理・廃棄物", 'param' => 5342, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "染み抜き", 'param' => 1900161, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "社会保険労務士", 'param' => 1973, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "証券・信託・商品先物", 'param' => 212, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "商品先物", 'param' => 1900170, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "情報提供サービス", 'param' => 5786, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "信用組合・信用金庫", 'param' => 3276, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "相談・調査", 'param' => 227, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "その他生活関連サービス", 'param' => 5277, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "代行・支援サービス", 'param' => 219, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "宅配便", 'param' => 213, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "探偵・興信所", 'param' => 1968, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "賃貸・レンタル", 'param' => 214, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "鉄道・飛行機・バス", 'param' => 4435, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "テレビ・ラジオ・新聞", 'param' => 216, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "電話・電話機", 'param' => 1900145, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "時計・修理", 'param' => 228, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "土地家屋調査士", 'param' => 1986, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "トランクルーム", 'param' => 1904, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ノンバンク・貸金", 'param' => 1890, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "パソコン・コンピュータ", 'param' => 1900148, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "パソコン購入・修理", 'param' => 2012, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "花屋", 'param' => 9554, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "風水・四柱推命", 'param' => 223, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "ふとんレンタル", 'param' => 1920, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "船・フェリー", 'param' => 4437, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "振袖・着物レンタル", 'param' => 1020, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "弁理士", 'param' => 1958, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "便利屋", 'param' => 1991, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "宝石・貴金属買取", 'param' => 1900151, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "保険", 'param' => 2004, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 5, 'title' => "レンタルショップ", 'param' => 1993, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 1, 'title' => "弁当・宅配", 'param' => 31, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "食堂・レストラン", 'param' => 43, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "焼肉・ステーキ・すき焼き", 'param' => 42, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "居酒屋", 'param' => 9536, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "割烹・料亭", 'param' => 523, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "魚・うなぎ・かき・かに", 'param' => 37, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "そば・うどん", 'param' => 39, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "すし", 'param' => 38, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "バー・スナック", 'param' => 403, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "スイーツ・和洋菓子", 'param' => 28, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "アジア・アフリカ料理", 'param' => 4058, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "アメリカ・中南米料理", 'param' => 548, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "イタリアン・フレンチ", 'param' => 29, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "欧風料理", 'param' => 4048, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "カレー", 'param' => 34, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "喫茶店・カフェ", 'param' => 33, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "郷土料理店", 'param' => 35, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "たこ焼き・お好み焼き", 'param' => 36, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "中華・中国料理", 'param' => 40, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "鳥・焼き鳥", 'param' => 475, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "丼・バーガー・ドーナツ", 'param' => 41, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "肉料理", 'param' => 473, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "飲み屋・パブ・クラブ", 'param' => 30, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "ラーメン", 'param' => 44, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 1, 'title' => "和食・日本料理", 'param' => 45, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 2, 'title' => "リフォーム", 'param' => 80, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "鍵屋", 'param' => 896, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "不動産屋・不動産取引", 'param' => 92, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "引越し運送", 'param' => 81, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "サイディング", 'param' => 1900048, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "畳・ふすま・障子", 'param' => 842, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "家具・インテリア", 'param' => 85, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "屋根・屋根工事", 'param' => 835, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "インテリアデザイン", 'param' => 3789, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "電器店・電器修理", 'param' => 1900039, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "椅子修理", 'param' => 1900044, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "エアコン・換気扇", 'param' => 86, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "エクステリア", 'param' => 83, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "ガーデニング・園芸", 'param' => 88, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "解体", 'param' => 1900047, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "ガス・ガス器具", 'param' => 1963, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "ガラス・ガラス修理", 'param' => 923, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "瓦・かわら", 'param' => 1900061, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "警備", 'param' => 2079, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "建材", 'param' => 82, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "建設業・工務店", 'param' => 84, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "建築・設計", 'param' => 9569, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "コンサルタント・コンサルティング", 'param' => 2161, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "シャッター・雨戸", 'param' => 824, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "住宅管理会社", 'param' => 1900031, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "住宅相談・調査", 'param' => 93, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "消防用品", 'param' => 898, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "シロアリ・ハチ駆除・消毒", 'param' => 218, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "寝具・ふとん", 'param' => 90, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "清掃", 'param' => 867, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "石材", 'param' => 1900021, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "造園", 'param' => 95, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "太陽光発電", 'param' => 847, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "暖房", 'param' => 1900041, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "電気・電力", 'param' => 87, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "電気工事", 'param' => 9532, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "トイレ・浴槽つまり清掃", 'param' => 1900064, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "塗装・ペイント", 'param' => 829, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "内装工事", 'param' => 806, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "配管・防水", 'param' => 1900062, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "ハウスクリーニング", 'param' => 868, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "バス・トイレ・キッチン", 'param' => 79, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "板金", 'param' => 1900050, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "ボイラー・風呂釜", 'param' => 2147, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "防水・防水工事", 'param' => 833, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "防犯用品", 'param' => 899, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "マンション・アパート賃貸", 'param' => 1900029, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 2, 'title' => "マンション・一戸建て購入", 'param' => 1900028, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 9586, 'title' => "あん摩・はり・きゅう", 'param' => 58, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "整体等各種療術", 'param' => 376, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "接骨・柔道整復", 'param' => 9462, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "介護サービス", 'param' => 1900416, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "老人ホーム・特養ホーム", 'param' => 4161, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "介護福祉タクシー", 'param' => 772, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "薬局・置き薬", 'param' => 753, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "カイロプラクティック", 'param' => 719, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "心理・電気療法等", 'param' => 1900411, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "福祉・社会福祉", 'param' => 374, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "介護施設", 'param' => 1900413, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "介護用品・福祉用具", 'param' => 1900415, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "漢方・漢方薬", 'param' => 750, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "薬", 'param' => 73, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "健康食品・自然食品", 'param' => 63, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "バンク", 'param' => 4118, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "訪問介護", 'param' => 698, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "保健衛生", 'param' => 4165, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9586, 'title' => "臨床検査", 'param' => 78, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 6, 'title' => "リサイクルショップ", 'param' => 119, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "印鑑・はんこ", 'param' => 1205, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "生活用品", 'param' => 121, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "めがね・補聴器・コンタクトレンズ", 'param' => 1181, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "おもちゃ・ゲーム", 'param' => 112, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "自転車", 'param' => 9547, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "スポーツ用品", 'param' => 115, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "アウトレットモール", 'param' => 4518, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "おみやげ", 'param' => 122, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "牛乳・乳製品店", 'param' => 1164, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "靴・かばん・小物", 'param' => 109, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "コーヒー・紅茶・飲料品", 'param' => 120, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "米屋・米店・もち", 'param' => 1106, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "コンビニエンスストア", 'param' => 113, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "魚・海産物店", 'param' => 1900194, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "酒・ワイン", 'param' => 1900185, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "CD・DVD・ビデオ・レコード", 'param' => 110, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "下着・シャツ", 'param' => 108, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "食品、食料品", 'param' => 114, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "スーパー・生協", 'param' => 1100, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "青果店", 'param' => 1110, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "惣菜店", 'param' => 1112, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "贈答品・ギフトショップ", 'param' => 122, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "その他ショッピング", 'param' => 4532, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "卵店", 'param' => 1113, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "チケット販売・買取", 'param' => 116, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "調味料店", 'param' => 1900195, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "通販", 'param' => 123, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "デパート・百貨店", 'param' => 1102, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "豆腐・豆製品店", 'param' => 1900196, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "肉屋・精肉店", 'param' => 1900192, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "人形店", 'param' => 1097, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "パン・ベーカリー店", 'param' => 5241, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "乾物店", 'param' => 1125, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "文具・事務用品店", 'param' => 124, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "ベビー・子ども用品", 'param' => 117, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 6, 'title' => "本・書籍販売", 'param' => 118, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 4, 'title' => "美容院", 'param' => 1028, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "宝石・時計・貴金属", 'param' => 96, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "貸衣裳", 'param' => 101, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "エステ・サロン", 'param' => 1022, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "洋服・仕立て直し", 'param' => 1015, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "床屋・理容店・散髪", 'param' => 1030, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "レディース・婦人服", 'param' => 1036, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "靴・履物・修理", 'param' => 1016, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "衣料品・子供服", 'param' => 100, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "かさ・修理", 'param' => 5249, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "かばん・バック・修理", 'param' => 1059, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "化粧品・コスメ", 'param' => 1900113, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "制服・作業服", 'param' => 104, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "ボディペイント", 'param' => 1900112, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "メンズ・紳士服", 'param' => 1034, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "毛髪業", 'param' => 1050, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "ランジェリー", 'param' => 5001, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 4, 'title' => "和服", 'param' => 105, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 9, 'title' => "総合・職別工事業", 'param' => 4216, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "その他製造・加工", 'param' => 253, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "金属製品製造・加工", 'param' => 246, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "運送・貨物・倉庫", 'param' => 240, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "工作機械・一般機械器具販売・卸", 'param' => 245, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "食品・食料品販売・卸", 'param' => 257, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "農業", 'param' => 267, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "印刷", 'param' => 2088, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "廃棄物処理", 'param' => 230, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "IT・情報通信", 'param' => 233, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "アウトソーシング", 'param' => 229, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "一般機械販売・卸", 'param' => 269, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "イベント", 'param' => 235, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "医薬・化粧品販売・卸", 'param' => 260, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "医療・薬関連製造・加工", 'param' => 254, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "衣料関連製造・加工", 'param' => 256, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "衣料関連販売・卸", 'param' => 259, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "印刷・出版", 'param' => 231, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "OA機器", 'param' => 234, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "化学・プラスチック製造・加工", 'param' => 252, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "家具・建具等販売・卸", 'param' => 6137, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "環境", 'param' => 274, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "鑑定・鑑定業", 'param' => 3619, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "機械器具販売・卸", 'param' => 6128, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "行政書士士会", 'param' => 1900291, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "建設資材販売・卸", 'param' => 250, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "建築資材製造・加工", 'param' => 255, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "鉱業", 'param' => 3845, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "広告・マーケティング", 'param' => 232, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "工作機械・一般機械器具製造・加工", 'param' => 236, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "公認会計士会", 'param' => 1900290, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "鉱物・金属材料販売・卸", 'param' => 6238, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "士業・コンサルタント", 'param' => 238, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "自動車卸", 'param' => 6123, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "司法書士士会", 'param' => 1900289, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "社会保険調査士会", 'param' => 1900288, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "車両・機械・器具修理", 'param' => 5429, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "出版社", 'param' => 1496, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "商社・貿易", 'param' => 266, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "食品・食料品製造・加工", 'param' => 244, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "水産業", 'param' => 3910, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "生活雑貨・日用品製造・加工", 'param' => 258, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "税理士会", 'param' => 1979, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "石油・石炭製品製造・加工", 'param' => 8498, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "設備工事業", 'param' => 241, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "専門サービス業", 'param' => 5466, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "装置・設備製造・加工", 'param' => 247, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "その他サービス", 'param' => 5483, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "ソフトウェア", 'param' => 5919, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "著述・芸術家", 'param' => 3649, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "鉄鋼製品製造・加工", 'param' => 265, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "電気機械器具製造・加工", 'param' => 264, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "電気機械器具販売・卸", 'param' => 6121, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "電子・精密機械器具製造・加工", 'param' => 268, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "土地家屋調査士会", 'param' => 5968, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "日用品販売・卸", 'param' => 261, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "販売・卸（その他）", 'param' => 262, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "非鉄金属製品製造・加工", 'param' => 270, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "ビルメンテナンス", 'param' => 237, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "不動産賃貸・管理", 'param' => 243, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "弁護士会", 'param' => 5961, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "弁理士事務会", 'param' => 1900292, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "翻訳・通訳", 'param' => 3626, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "木製品・紙・パルプ関連製造・加工", 'param' => 272, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "輸送機械器具製造・加工", 'param' => 242, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "窯業・土石製造・加工", 'param' => 8494, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "リース・レンタル", 'param' => 239, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 9, 'title' => "林業", 'param' => 3843, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 7, 'title' => "動物病院・獣医師", 'param' => 199, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ペット霊園・葬儀", 'param' => 197, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ペット美容室・トリミング", 'param' => 196, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ペットショップ", 'param' => 194, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ペットホテル", 'param' => 195, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ペットサービス", 'param' => 193, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 7, 'title' => "ブリーダー・犬訓練所", 'param' => 198, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 8, 'title' => "旅館・民宿", 'param' => 46, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "ホテル", 'param' => 50, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "ビジネスホテル", 'param' => 621, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "バス・観光バス", 'param' => 610, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "レンタカー", 'param' => 635, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "観光・観光案内", 'param' => 49, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "旅行・チケット販売", 'param' => 47, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "道の駅", 'param' => 53, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "銭湯・サウナ", 'param' => 665, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "温泉", 'param' => 49, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "観光・温泉・銭湯", 'param' => 49, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "キャンプ", 'param' => 51, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "果物・果樹園", 'param' => 605, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "公共宿泊施設", 'param' => 52, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "宿泊施設・宿泊所", 'param' => 57, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "ペンション", 'param' => 673, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "牧場", 'param' => 9541, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "ホテル・旅館予約", 'param' => 54, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 8, 'title' => "モーテル・ラブホテル", 'param' => 56, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 13, 'title' => "スポーツ施設", 'param' => 176, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "プレイスポット", 'param' => 174, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "アウトドア", 'param' => 181, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "フィットネス", 'param' => 183, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "屋内遊戯", 'param' => 177, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "釣り", 'param' => 192, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "博物館・美術館", 'param' => 178, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "ウィンタースポーツ", 'param' => 190, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "映画・劇場", 'param' => 173, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "屋外遊戯", 'param' => 186, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "公営競技", 'param' => 185, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "娯楽・漫才・寄席", 'param' => 5787, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "ゴルフ", 'param' => 175, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "ゴルフ場", 'param' => 1684, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "ゴルフ練習場", 'param' => 1685, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "サッカー", 'param' => 188, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "テニス", 'param' => 184, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "動物園・植物園・水族館", 'param' => 4247, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "ホール・会館", 'param' => 2855, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "マンガ・ネットカフェ", 'param' => 182, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 13, 'title' => "モータースポーツ", 'param' => 179, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 15, 'title' => "車検・整備・修理", 'param' => 128, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "自動車販売・管理", 'param' => 125, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "タイヤ・カー用品", 'param' => 131, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "ガソリンスタンド", 'param' => 135, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "中古車・買取", 'param' => 132, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "バイク販売・用品", 'param' => 127, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "洗車・コーティング", 'param' => 130, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "駐車場・パーキング", 'param' => 136, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "自動車解体", 'param' => 1225, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "バイク中古・買取", 'param' => 134, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "フロントガラス", 'param' => 1900393, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 15, 'title' => "レッカー・ロードサービス", 'param' => 1242, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 11, 'title' => "楽器購入・買取", 'param' => 1406, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "骨とう・古物", 'param' => 145, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "模型(プラモ)・ラジコン", 'param' => 152, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "画家・陶芸家・工芸家", 'param' => 3656, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "楽器修理・調律", 'param' => 144, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "ミシン・編機", 'param' => 1900342, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "囲碁・将棋・ボード", 'param' => 151, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "音楽家", 'param' => 3695, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "音楽制作・スタジオ", 'param' => 5872, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "額縁・額装", 'param' => 1341, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "キャラクタ", 'param' => 1900333, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "ギャラリー・画廊", 'param' => 1467, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "裁縫・手芸", 'param' => 146, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "材料", 'param' => 1900337, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "たばこ・喫煙", 'param' => 147, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "美術・陶芸・工芸品", 'param' => 148, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "古本・貸本", 'param' => 1158, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "望遠鏡・天文", 'param' => 5192, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "ホームクラフト", 'param' => 156, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 11, 'title' => "ライター・評論家", 'param' => 3618, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 14,'title' =>  "葬儀", 'param' => 139, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 14,'title' =>  "宗教", 'param' => 138, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 14,'title' =>  "写真・ビデオ・スライド", 'param' => 142, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 14,'title' =>  "仏壇・仏具・神具", 'param' => 140, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 14,'title' =>  "結婚・宴会", 'param' => 141, 'created_at' => $dt,  'updated_at' => $dt ],


            ['genre_id' => 10,'title' =>  "幼稚園・保育施設", 'param' => 167, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "楽器・音楽教室", 'param' => 158, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "スポーツクラブ・教室", 'param' => 162, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "各種学校", 'param' => 168, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "カルチャースクール", 'param' => 1665, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "バレエ・ダンス教室", 'param' => 1667, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "塾・予備校", 'param' => 161, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "語学・会話・スクール", 'param' => 170, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "美術・工芸教室", 'param' => 4504, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "求人・就職・派遣", 'param' => 169, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "華道・茶道", 'param' => 163, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "資格", 'param' => 160, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "小・中・高・大学等", 'param' => 159, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "書道・そろばん", 'param' => 172, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "スポーツ関連クラブ", 'param' => 4331, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "専修学校", 'param' => 164, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "特殊教育諸学校", 'param' => 165, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "トレーニング", 'param' => 1900308, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "武道・格闘技", 'param' => 4480, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "マリンスポーツ", 'param' => 4441, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "幼児教室", 'param' => 166, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "ヨガ・エクササイズ", 'param' => 1787, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 10,'title' =>  "料理教室", 'param' => 1669, 'created_at' => $dt,  'updated_at' => $dt ],

            ['genre_id' => 12,'title' =>  "市区役所・町村役場", 'param' => 1834, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "市区町村機関", 'param' => 202, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "組合・団体", 'param' => 201, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "消防・警察", 'param' => 203, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "公民館・集会場", 'param' => 1880, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "図書館", 'param' => 208, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "都道府県庁・機関", 'param' => 206, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "外国公館", 'param' => 5777, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "官公署", 'param' => 204, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "公庫・公社・事業団", 'param' => 209, 'created_at' => $dt,  'updated_at' => $dt ],
            ['genre_id' => 12,'title' =>  "裁判所", 'param' => 205, 'created_at' => $dt,  'updated_at' => $dt ],


        ]);

    }
}