<?php

use Illuminate\Database\Seeder;
use App\Genre;
use App\SubGenre;

class SubGenresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SubGenre::insert([
            ['genre_id' => 9585, 'title' => "歯科", 'param' => 65],
            ['genre_id' => 9585, 'title' => "矯正歯科", 'param' => 9646],
            ['genre_id' => 9585, 'title' => "小児歯科", 'param' => 9644],
            ['genre_id' => 9585, 'title' => "歯科口腔外科", 'param' => 9645],
            ['genre_id' => 9585, 'title' => "デンタルドック", 'param' => 9647],

            // ['genre_id' => 3, 'title' => "内科", 'param' => 70],
            // ['genre_id' => 3, 'title' => "眼科", 'param' => 62],
            // ['genre_id' => 3, 'title' => "整形外科", 'param' => 9621],
            // ['genre_id' => 3, 'title' => "耳鼻咽喉科", 'param' => 66],
            // ['genre_id' => 3, 'title' => "皮膚科", 'param' => 72],
            // ['genre_id' => 3, 'title' => "小児科", 'param' => 67],
            // ['genre_id' => 3, 'title' => "産婦人科", 'param' => 64],
            // ['genre_id' => 3, 'title' => "診療所・療養所", 'param' => 74],
            // ['genre_id' => 3, 'title' => "外科", 'param' => 60],
            // ['genre_id' => 3, 'title' => "精神科", 'param' => 69],
            // ['genre_id' => 3, 'title' => "アレルギー科", 'param' => 9624],
            // ['genre_id' => 3, 'title' => "胃腸消化器科", 'param' => 9625],
            // ['genre_id' => 3, 'title' => "気管食道外科", 'param' => 9630],
            // ['genre_id' => 3, 'title' => "休日・夜間診療機関", 'param' => 75],
            // ['genre_id' => 3, 'title' => "休日夜間医療", 'param' => 75],
            // ['genre_id' => 3, 'title' => "形成外科", 'param' => 9622],
            // ['genre_id' => 3, 'title' => "肛門科", 'param' => 9459],
            // ['genre_id' => 3, 'title' => "呼吸器科", 'param' => 9635],
            // ['genre_id' => 3, 'title' => "循環器科", 'param' => 9632],
            // ['genre_id' => 3, 'title' => "小児科系", 'param' => 67],
            // ['genre_id' => 3, 'title' => "小児外科", 'param' => 9620],
            // ['genre_id' => 3, 'title' => "助産師・助産所", 'param' => 9640],
            // ['genre_id' => 3, 'title' => "神経内科", 'param' => 9612],
            // ['genre_id' => 3, 'title' => "心臓血管外科", 'param' => 9616],
            // ['genre_id' => 3, 'title' => "心療内科", 'param' => 9613],
            // ['genre_id' => 3, 'title' => "性感染症科", 'param' => 9642],
            // ['genre_id' => 3, 'title' => "総合病院", 'param' => 76],
            // ['genre_id' => 3, 'title' => "乳腺外科", 'param' => 9618],
            // ['genre_id' => 3, 'title' => "人間ドック", 'param' => 68],
            // ['genre_id' => 3, 'title' => "脳神経外科", 'param' => 9615],
            // ['genre_id' => 3, 'title' => "泌尿器科", 'param' => 71],
            // ['genre_id' => 3, 'title' => "美容外科", 'param' => 9623],
            // ['genre_id' => 3, 'title' => "婦人科", 'param' => 9641],
            // ['genre_id' => 3, 'title' => "放射線科", 'param' => 77],
            // ['genre_id' => 3, 'title' => "ホスピス・緩和ケア", 'param' => 9610],
            // ['genre_id' => 3, 'title' => "麻酔科", 'param' => 9643],
            // ['genre_id' => 3, 'title' => "リウマチ科", 'param' => 717],
            // ['genre_id' => 3, 'title' => "リハビリテーション", 'param' => 9614],
            // ['genre_id' => 3, 'title' => "リハビリテーション科", 'param' => 9450],

            // ['genre_id' => 5, 'title' => "美容院", 'param' => 1028],
            // ['genre_id' => 5, 'title' => "宝石・時計・貴金属", 'param' => 96],
            // ['genre_id' => 5, 'title' => "貸衣裳", 'param' => 101],
            // ['genre_id' => 5, 'title' => "エステ・サロン", 'param' => 1022],
            // ['genre_id' => 5, 'title' => "洋服・仕立て直し", 'param' => 1015],
            // ['genre_id' => 5, 'title' => "床屋・理容店・散髪", 'param' => 1030],
            // ['genre_id' => 5, 'title' => "レディース・婦人服", 'param' => 1036],
            // ['genre_id' => 5, 'title' => "靴・履物・修理", 'param' => 1016],
            // ['genre_id' => 5, 'title' => "衣料品・子供服", 'param' => 100],
            // ['genre_id' => 5, 'title' => "かさ・修理", 'param' => 5249],
            // ['genre_id' => 5, 'title' => "かばん・バック・修理", 'param' => 1059],
            // ['genre_id' => 5, 'title' => "化粧品・コスメ", 'param' => 1900113],
            // ['genre_id' => 5, 'title' => "制服・作業服", 'param' => 104],
            // ['genre_id' => 5, 'title' => "ボディペイント", 'param' => 1900112],
            // ['genre_id' => 5, 'title' => "メンズ・紳士服", 'param' => 1034],
            // ['genre_id' => 5, 'title' => "毛髪業", 'param' => 1050],
            // ['genre_id' => 5, 'title' => "ランジェリー", 'param' => 5001],
            // ['genre_id' => 5, 'title' => "和服", 'param' => 105],
            // ['genre_id' => 5, 'title' => "水道", 'param' => 1900153],
            // ['genre_id' => 5, 'title' => "税理士", 'param' => 1979],
            // ['genre_id' => 5, 'title' => "弁護士", 'param' => 1990],
            // ['genre_id' => 5, 'title' => "司法書士", 'param' => 1972],
            // ['genre_id' => 5, 'title' => "リサイクルショップ", 'param' => 119],
            // ['genre_id' => 5, 'title' => "質屋", 'param' => 1971],
            // ['genre_id' => 5, 'title' => "タクシー", 'param' => 225],
            // ['genre_id' => 5, 'title' => "写真・スタジオ", 'param' => 224],
            // ['genre_id' => 5, 'title' => "家具修理・雑貨修理", 'param' => 5244],
            // ['genre_id' => 5, 'title' => "ごみ収集・資源回収", 'param' => 217],
            // ['genre_id' => 5, 'title' => "インターネット", 'param' => 1900147],
            // ['genre_id' => 5, 'title' => "占い・手相", 'param' => 143],
            // ['genre_id' => 5, 'title' => "運転代行", 'param' => 5326],
            // ['genre_id' => 5, 'title' => "家政婦紹介", 'param' => 1923],
            // ['genre_id' => 5, 'title' => "行政書士", 'param' => 1966],
            // ['genre_id' => 5, 'title' => "銀行・郵貯", 'param' => 1891],
            // ['genre_id' => 5, 'title' => "空港・飛行機・ヘリ", 'param' => 4350],
            // ['genre_id' => 5, 'title' => "クリーニング・コインランドリー", 'param' => 215],
            // ['genre_id' => 5, 'title' => "携帯・スマホ", 'param' => 2014],
            // ['genre_id' => 5, 'title' => "ごみ処理・廃棄物", 'param' => 5342],
            // ['genre_id' => 5, 'title' => "染み抜き", 'param' => 1900161],
            // ['genre_id' => 5, 'title' => "社会保険労務士", 'param' => 1973],
            // ['genre_id' => 5, 'title' => "証券・信託・商品先物", 'param' => 212],
            // ['genre_id' => 5, 'title' => "商品先物", 'param' => 1900170],
            // ['genre_id' => 5, 'title' => "情報提供サービス", 'param' => 5786],
            // ['genre_id' => 5, 'title' => "信用組合・信用金庫", 'param' => 3276],
            // ['genre_id' => 5, 'title' => "相談・調査", 'param' => 227],
            // ['genre_id' => 5, 'title' => "その他生活関連サービス", 'param' => 5277],
            // ['genre_id' => 5, 'title' => "代行・支援サービス", 'param' => 219],
            // ['genre_id' => 5, 'title' => "宅配便", 'param' => 213],
            // ['genre_id' => 5, 'title' => "探偵・興信所", 'param' => 1968],
            // ['genre_id' => 5, 'title' => "賃貸・レンタル", 'param' => 214],
            // ['genre_id' => 5, 'title' => "鉄道・飛行機・バス", 'param' => 4435],
            // ['genre_id' => 5, 'title' => "テレビ・ラジオ・新聞", 'param' => 216],
            // ['genre_id' => 5, 'title' => "電話・電話機", 'param' => 1900145],
            // ['genre_id' => 5, 'title' => "時計・修理", 'param' => 228],
            // ['genre_id' => 5, 'title' => "土地家屋調査士", 'param' => 1986],
            // ['genre_id' => 5, 'title' => "トランクルーム", 'param' => 1904],
            // ['genre_id' => 5, 'title' => "ノンバンク・貸金", 'param' => 1890],
            // ['genre_id' => 5, 'title' => "パソコン・コンピュータ", 'param' => 1900148],
            // ['genre_id' => 5, 'title' => "パソコン購入・修理", 'param' => 2012],
            // ['genre_id' => 5, 'title' => "花屋", 'param' => 9554],
            // ['genre_id' => 5, 'title' => "風水・四柱推命", 'param' => 223],
            // ['genre_id' => 5, 'title' => "ふとんレンタル", 'param' => 1920],
            // ['genre_id' => 5, 'title' => "船・フェリー", 'param' => 4437],
            // ['genre_id' => 5, 'title' => "振袖・着物レンタル", 'param' => 1020],
            // ['genre_id' => 5, 'title' => "弁理士", 'param' => 1958],
            // ['genre_id' => 5, 'title' => "便利屋", 'param' => 1991],
            // ['genre_id' => 5, 'title' => "宝石・貴金属買取", 'param' => 1900151],
            // ['genre_id' => 5, 'title' => "保険", 'param' => 2004],
            // ['genre_id' => 5, 'title' => "レンタルショップ", 'param' => 1993],


            // ['genre_id' => 1, 'title' => "弁当・宅配", 'param' => 31],
            // ['genre_id' => 1, 'title' => "食堂・レストラン", 'param' => 43],
            // ['genre_id' => 1, 'title' => "焼肉・ステーキ・すき焼き", 'param' => 42],
            // ['genre_id' => 1, 'title' => "居酒屋", 'param' => 9536],
            // ['genre_id' => 1, 'title' => "割烹・料亭", 'param' => 523],
            // ['genre_id' => 1, 'title' => "魚・うなぎ・かき・かに", 'param' => 37],
            // ['genre_id' => 1, 'title' => "そば・うどん", 'param' => 39],
            // ['genre_id' => 1, 'title' => "すし", 'param' => 38],
            // ['genre_id' => 1, 'title' => "バー・スナック", 'param' => 403],
            // ['genre_id' => 1, 'title' => "スイーツ・和洋菓子", 'param' => 28],
            // ['genre_id' => 1, 'title' => "アジア・アフリカ料理", 'param' => 4058],
            // ['genre_id' => 1, 'title' => "アメリカ・中南米料理", 'param' => 548],
            // ['genre_id' => 1, 'title' => "イタリアン・フレンチ", 'param' => 29],
            // ['genre_id' => 1, 'title' => "欧風料理", 'param' => 4048],
            // ['genre_id' => 1, 'title' => "カレー", 'param' => 34],
            // ['genre_id' => 1, 'title' => "喫茶店・カフェ", 'param' => 33],
            // ['genre_id' => 1, 'title' => "郷土料理店", 'param' => 35],
            // ['genre_id' => 1, 'title' => "たこ焼き・お好み焼き", 'param' => 36],
            // ['genre_id' => 1, 'title' => "中華・中国料理", 'param' => 40],
            // ['genre_id' => 1, 'title' => "鳥・焼き鳥", 'param' => 475],
            // ['genre_id' => 1, 'title' => "丼・バーガー・ドーナツ", 'param' => 41],
            // ['genre_id' => 1, 'title' => "肉料理", 'param' => 473],
            // ['genre_id' => 1, 'title' => "飲み屋・パブ・クラブ", 'param' => 30],
            // ['genre_id' => 1, 'title' => "ラーメン", 'param' => 44],
            // ['genre_id' => 1, 'title' => "和食・日本料理", 'param' => 45],


            // ['genre_id' => 2, 'title' => "リフォーム", 'param' => 80],
            // ['genre_id' => 2, 'title' => "鍵屋", 'param' => 896],
            // ['genre_id' => 2, 'title' => "不動産屋・不動産取引", 'param' => 92],
            // ['genre_id' => 2, 'title' => "引越し運送", 'param' => 81],
            // ['genre_id' => 2, 'title' => "サイディング", 'param' => 1900048],
            // ['genre_id' => 2, 'title' => "畳・ふすま・障子", 'param' => 842],
            // ['genre_id' => 2, 'title' => "家具・インテリア", 'param' => 85],
            // ['genre_id' => 2, 'title' => "屋根・屋根工事", 'param' => 835],
            // ['genre_id' => 2, 'title' => "インテリアデザイン", 'param' => 3789],
            // ['genre_id' => 2, 'title' => "電器店・電器修理", 'param' => 1900039],
            // ['genre_id' => 2, 'title' => "椅子修理", 'param' => 1900044],
            // ['genre_id' => 2, 'title' => "エアコン・換気扇", 'param' => 86],
            // ['genre_id' => 2, 'title' => "エクステリア", 'param' => 83],
            // ['genre_id' => 2, 'title' => "ガーデニング・園芸", 'param' => 88],
            // ['genre_id' => 2, 'title' => "解体", 'param' => 1900047],
            // ['genre_id' => 2, 'title' => "ガス・ガス器具", 'param' => 1963],
            // ['genre_id' => 2, 'title' => "ガラス・ガラス修理", 'param' => 923],
            // ['genre_id' => 2, 'title' => "瓦・かわら", 'param' => 1900061],
            // ['genre_id' => 2, 'title' => "警備", 'param' => 2079],
            // ['genre_id' => 2, 'title' => "建材", 'param' => 82],
            // ['genre_id' => 2, 'title' => "建設業・工務店", 'param' => 84],
            // ['genre_id' => 2, 'title' => "建築・設計", 'param' => 9569],
            // ['genre_id' => 2, 'title' => "コンサルタント・コンサルティング", 'param' => 2161],
            // ['genre_id' => 2, 'title' => "シャッター・雨戸", 'param' => 824],
            // ['genre_id' => 2, 'title' => "住宅管理会社", 'param' => 1900031],
            // ['genre_id' => 2, 'title' => "住宅相談・調査", 'param' => 93],
            // ['genre_id' => 2, 'title' => "消防用品", 'param' => 898],
            // ['genre_id' => 2, 'title' => "シロアリ・ハチ駆除・消毒", 'param' => 218],
            // ['genre_id' => 2, 'title' => "寝具・ふとん", 'param' => 90],
            // ['genre_id' => 2, 'title' => "清掃", 'param' => 867],
            // ['genre_id' => 2, 'title' => "石材", 'param' => 1900021],
            // ['genre_id' => 2, 'title' => "造園", 'param' => 95],
            // ['genre_id' => 2, 'title' => "太陽光発電", 'param' => 847],
            // ['genre_id' => 2, 'title' => "暖房", 'param' => 1900041],
            // ['genre_id' => 2, 'title' => "電気・電力", 'param' => 87],
            // ['genre_id' => 2, 'title' => "電気工事", 'param' => 9532],
            // ['genre_id' => 2, 'title' => "トイレ・浴槽つまり清掃", 'param' => 1900064],
            // ['genre_id' => 2, 'title' => "塗装・ペイント", 'param' => 829],
            // ['genre_id' => 2, 'title' => "内装工事", 'param' => 806],
            // ['genre_id' => 2, 'title' => "配管・防水", 'param' => 1900062],
            // ['genre_id' => 2, 'title' => "ハウスクリーニング", 'param' => 868],
            // ['genre_id' => 2, 'title' => "バス・トイレ・キッチン", 'param' => 79],
            // ['genre_id' => 2, 'title' => "板金", 'param' => 1900050],
            // ['genre_id' => 2, 'title' => "ボイラー・風呂釜", 'param' => 2147],
            // ['genre_id' => 2, 'title' => "防水・防水工事", 'param' => 833],
            // ['genre_id' => 2, 'title' => "防犯用品", 'param' => 899],
            // ['genre_id' => 2, 'title' => "マンション・アパート賃貸", 'param' => 1900029],
            // ['genre_id' => 2, 'title' => "マンション・一戸建て購入", 'param' => 1900028],


            // ['genre_id' => 9586, 'title' => "あん摩・はり・きゅう", 'param' => 58],
            // ['genre_id' => 9586, 'title' => "整体等各種療術", 'param' => 376],
            // ['genre_id' => 9586, 'title' => "接骨・柔道整復", 'param' => 9462],
            // ['genre_id' => 9586, 'title' => "介護サービス", 'param' => 1900416],
            // ['genre_id' => 9586, 'title' => "老人ホーム・特養ホーム", 'param' => 4161],
            // ['genre_id' => 9586, 'title' => "介護福祉タクシー", 'param' => 772],
            // ['genre_id' => 9586, 'title' => "薬局・置き薬", 'param' => 753],
            // ['genre_id' => 9586, 'title' => "カイロプラクティック", 'param' => 719],
            // ['genre_id' => 9586, 'title' => "心理・電気療法等", 'param' => 1900411],
            // ['genre_id' => 9586, 'title' => "福祉・社会福祉", 'param' => 374],
            // ['genre_id' => 9586, 'title' => "介護施設", 'param' => 1900413],
            // ['genre_id' => 9586, 'title' => "介護用品・福祉用具", 'param' => 1900415],
            // ['genre_id' => 9586, 'title' => "漢方・漢方薬", 'param' => 750],
            // ['genre_id' => 9586, 'title' => "薬", 'param' => 73],
            // ['genre_id' => 9586, 'title' => "健康食品・自然食品", 'param' => 63],
            // ['genre_id' => 9586, 'title' => "バンク", 'param' => 4118],
            // ['genre_id' => 9586, 'title' => "訪問介護", 'param' => 698],
            // ['genre_id' => 9586, 'title' => "保健衛生", 'param' => 4165],
            // ['genre_id' => 9586, 'title' => "臨床検査", 'param' => 78],

            // ['genre_id' => 6, 'title' => "リサイクルショップ", 'param' => 119],
            // ['genre_id' => 6, 'title' => "印鑑・はんこ", 'param' => 1205],
            // ['genre_id' => 6, 'title' => "生活用品", 'param' => 121],
            // ['genre_id' => 6, 'title' => "めがね・補聴器・コンタクトレンズ", 'param' => 1181],
            // ['genre_id' => 6, 'title' => "おもちゃ・ゲーム", 'param' => 112],
            // ['genre_id' => 6, 'title' => "自転車", 'param' => 9547],
            // ['genre_id' => 6, 'title' => "スポーツ用品", 'param' => 115],
            // ['genre_id' => 6, 'title' => "アウトレットモール", 'param' => 4518],
            // ['genre_id' => 6, 'title' => "おみやげ", 'param' => 122],
            // ['genre_id' => 6, 'title' => "牛乳・乳製品店", 'param' => 1164],
            // ['genre_id' => 6, 'title' => "靴・かばん・小物", 'param' => 109],
            // ['genre_id' => 6, 'title' => "コーヒー・紅茶・飲料品", 'param' => 120],
            // ['genre_id' => 6, 'title' => "米屋・米店・もち", 'param' => 1106],
            // ['genre_id' => 6, 'title' => "コンビニエンスストア", 'param' => 113],
            // ['genre_id' => 6, 'title' => "魚・海産物店", 'param' => 1900194],
            // ['genre_id' => 6, 'title' => "酒・ワイン", 'param' => 1900185],
            // ['genre_id' => 6, 'title' => "CD・DVD・ビデオ・レコード", 'param' => 110],
            // ['genre_id' => 6, 'title' => "下着・シャツ", 'param' => 108],
            // ['genre_id' => 6, 'title' => "食品、食料品", 'param' => 114],
            // ['genre_id' => 6, 'title' => "スーパー・生協", 'param' => 1100],
            // ['genre_id' => 6, 'title' => "青果店", 'param' => 1110],
            // ['genre_id' => 6, 'title' => "惣菜店", 'param' => 1112],
            // ['genre_id' => 6, 'title' => "贈答品・ギフトショップ", 'param' => 122],
            // ['genre_id' => 6, 'title' => "その他ショッピング", 'param' => 4532],
            // ['genre_id' => 6, 'title' => "卵店", 'param' => 1113],
            // ['genre_id' => 6, 'title' => "チケット販売・買取", 'param' => 116],
            // ['genre_id' => 6, 'title' => "調味料店", 'param' => 1900195],
            // ['genre_id' => 6, 'title' => "通販", 'param' => 123],
            // ['genre_id' => 6, 'title' => "デパート・百貨店", 'param' => 1102],
            // ['genre_id' => 6, 'title' => "豆腐・豆製品店", 'param' => 1900196],
            // ['genre_id' => 6, 'title' => "肉屋・精肉店", 'param' => 1900192],
            // ['genre_id' => 6, 'title' => "人形店", 'param' => 1097],
            // ['genre_id' => 6, 'title' => "パン・ベーカリー店", 'param' => 5241],
            // ['genre_id' => 6, 'title' => "乾物店", 'param' => 1125],
            // ['genre_id' => 6, 'title' => "文具・事務用品店", 'param' => 124],
            // ['genre_id' => 6, 'title' => "ベビー・子ども用品", 'param' => 117],
            // ['genre_id' => 6, 'title' => "本・書籍販売", 'param' => 118],


            // ['genre_id' => 4, 'title' => "美容院", 'param' => 1028],
            // ['genre_id' => 4, 'title' => "宝石・時計・貴金属", 'param' => 96],
            // ['genre_id' => 4, 'title' => "貸衣裳", 'param' => 101],
            // ['genre_id' => 4, 'title' => "エステ・サロン", 'param' => 1022],
            // ['genre_id' => 4, 'title' => "洋服・仕立て直し", 'param' => 1015],
            // ['genre_id' => 4, 'title' => "床屋・理容店・散髪", 'param' => 1030],
            // ['genre_id' => 4, 'title' => "レディース・婦人服", 'param' => 1036],
            // ['genre_id' => 4, 'title' => "靴・履物・修理", 'param' => 1016],
            // ['genre_id' => 4, 'title' => "衣料品・子供服", 'param' => 100],
            // ['genre_id' => 4, 'title' => "かさ・修理", 'param' => 5249],
            // ['genre_id' => 4, 'title' => "かばん・バック・修理", 'param' => 1059],
            // ['genre_id' => 4, 'title' => "化粧品・コスメ", 'param' => 1900113],
            // ['genre_id' => 4, 'title' => "制服・作業服", 'param' => 104],
            // ['genre_id' => 4, 'title' => "ボディペイント", 'param' => 1900112],
            // ['genre_id' => 4, 'title' => "メンズ・紳士服", 'param' => 1034],
            // ['genre_id' => 4, 'title' => "毛髪業", 'param' => 1050],
            // ['genre_id' => 4, 'title' => "ランジェリー", 'param' => 5001],
            // ['genre_id' => 4, 'title' => "和服", 'param' => 105],


            // ['genre_id' => 9, 'title' => "総合・職別工事業", 'param' => 4216],
            // ['genre_id' => 9, 'title' => "その他製造・加工", 'param' => 253],
            // ['genre_id' => 9, 'title' => "金属製品製造・加工", 'param' => 246],
            // ['genre_id' => 9, 'title' => "運送・貨物・倉庫", 'param' => 240],
            // ['genre_id' => 9, 'title' => "工作機械・一般機械器具販売・卸", 'param' => 245],
            // ['genre_id' => 9, 'title' => "食品・食料品販売・卸", 'param' => 257],
            // ['genre_id' => 9, 'title' => "農業", 'param' => 267],
            // ['genre_id' => 9, 'title' => "印刷", 'param' => 2088],
            // ['genre_id' => 9, 'title' => "廃棄物処理", 'param' => 230],
            // ['genre_id' => 9, 'title' => "IT・情報通信", 'param' => 233],
            // ['genre_id' => 9, 'title' => "アウトソーシング", 'param' => 229],
            // ['genre_id' => 9, 'title' => "一般機械販売・卸", 'param' => 269],
            // ['genre_id' => 9, 'title' => "イベント", 'param' => 235],
            // ['genre_id' => 9, 'title' => "医薬・化粧品販売・卸", 'param' => 260],
            // ['genre_id' => 9, 'title' => "医療・薬関連製造・加工", 'param' => 254],
            // ['genre_id' => 9, 'title' => "衣料関連製造・加工", 'param' => 256],
            // ['genre_id' => 9, 'title' => "衣料関連販売・卸", 'param' => 259],
            // ['genre_id' => 9, 'title' => "印刷・出版", 'param' => 231],
            // ['genre_id' => 9, 'title' => "OA機器", 'param' => 234],
            // ['genre_id' => 9, 'title' => "化学・プラスチック製造・加工", 'param' => 252],
            // ['genre_id' => 9, 'title' => "家具・建具等販売・卸", 'param' => 6137],
            // ['genre_id' => 9, 'title' => "環境", 'param' => 274],
            // ['genre_id' => 9, 'title' => "鑑定・鑑定業", 'param' => 3619],
            // ['genre_id' => 9, 'title' => "機械器具販売・卸", 'param' => 6128],
            // ['genre_id' => 9, 'title' => "行政書士士会", 'param' => 1900291],
            // ['genre_id' => 9, 'title' => "建設資材販売・卸", 'param' => 250],
            // ['genre_id' => 9, 'title' => "建築資材製造・加工", 'param' => 255],
            // ['genre_id' => 9, 'title' => "鉱業", 'param' => 3845],
            // ['genre_id' => 9, 'title' => "広告・マーケティング", 'param' => 232],
            // ['genre_id' => 9, 'title' => "工作機械・一般機械器具製造・加工", 'param' => 236],
            // ['genre_id' => 9, 'title' => "公認会計士会", 'param' => 1900290],
            // ['genre_id' => 9, 'title' => "鉱物・金属材料販売・卸", 'param' => 6238],
            // ['genre_id' => 9, 'title' => "士業・コンサルタント", 'param' => 238],
            // ['genre_id' => 9, 'title' => "自動車卸", 'param' => 6123],
            // ['genre_id' => 9, 'title' => "司法書士士会", 'param' => 1900289],
            // ['genre_id' => 9, 'title' => "社会保険調査士会", 'param' => 1900288],
            // ['genre_id' => 9, 'title' => "車両・機械・器具修理", 'param' => 5429],
            // ['genre_id' => 9, 'title' => "出版社", 'param' => 1496],
            // ['genre_id' => 9, 'title' => "商社・貿易", 'param' => 266],
            // ['genre_id' => 9, 'title' => "食品・食料品製造・加工", 'param' => 244],
            // ['genre_id' => 9, 'title' => "水産業", 'param' => 3910],
            // ['genre_id' => 9, 'title' => "生活雑貨・日用品製造・加工", 'param' => 258],
            // ['genre_id' => 9, 'title' => "税理士会", 'param' => 1979],
            // ['genre_id' => 9, 'title' => "石油・石炭製品製造・加工", 'param' => 8498],
            // ['genre_id' => 9, 'title' => "設備工事業", 'param' => 241],
            // ['genre_id' => 9, 'title' => "専門サービス業", 'param' => 5466],
            // ['genre_id' => 9, 'title' => "装置・設備製造・加工", 'param' => 247],
            // ['genre_id' => 9, 'title' => "その他サービス", 'param' => 5483],
            // ['genre_id' => 9, 'title' => "ソフトウェア", 'param' => 5919],
            // ['genre_id' => 9, 'title' => "著述・芸術家", 'param' => 3649],
            // ['genre_id' => 9, 'title' => "鉄鋼製品製造・加工", 'param' => 265],
            // ['genre_id' => 9, 'title' => "電気機械器具製造・加工", 'param' => 264],
            // ['genre_id' => 9, 'title' => "電気機械器具販売・卸", 'param' => 6121],
            // ['genre_id' => 9, 'title' => "電子・精密機械器具製造・加工", 'param' => 268],
            // ['genre_id' => 9, 'title' => "土地家屋調査士会", 'param' => 5968],
            // ['genre_id' => 9, 'title' => "日用品販売・卸", 'param' => 261],
            // ['genre_id' => 9, 'title' => "販売・卸（その他）", 'param' => 262],
            // ['genre_id' => 9, 'title' => "非鉄金属製品製造・加工", 'param' => 270],
            // ['genre_id' => 9, 'title' => "ビルメンテナンス", 'param' => 237],
            // ['genre_id' => 9, 'title' => "不動産賃貸・管理", 'param' => 243],
            // ['genre_id' => 9, 'title' => "弁護士会", 'param' => 5961],
            // ['genre_id' => 9, 'title' => "弁理士事務会", 'param' => 1900292],
            // ['genre_id' => 9, 'title' => "翻訳・通訳", 'param' => 3626],
            // ['genre_id' => 9, 'title' => "木製品・紙・パルプ関連製造・加工", 'param' => 272],
            // ['genre_id' => 9, 'title' => "輸送機械器具製造・加工", 'param' => 242],
            // ['genre_id' => 9, 'title' => "窯業・土石製造・加工", 'param' => 8494],
            // ['genre_id' => 9, 'title' => "リース・レンタル", 'param' => 239],
            // ['genre_id' => 9, 'title' => "林業", 'param' => 3843],

            // ['genre_id' => 7, 'title' => "動物病院・獣医師", 'param' => 199],
            // ['genre_id' => 7, 'title' => "ペット霊園・葬儀", 'param' => 197],
            // ['genre_id' => 7, 'title' => "ペット美容室・トリミング", 'param' => 196],
            // ['genre_id' => 7, 'title' => "ペットショップ", 'param' => 194],
            // ['genre_id' => 7, 'title' => "ペットホテル", 'param' => 195],
            // ['genre_id' => 7, 'title' => "ペットサービス", 'param' => 193],
            // ['genre_id' => 7, 'title' => "ブリーダー・犬訓練所", 'param' => 198],


            // ['genre_id' => 8, 'title' => "旅館・民宿", 'param' => 46],
            // ['genre_id' => 8, 'title' => "ホテル", 'param' => 50],
            // ['genre_id' => 8, 'title' => "ビジネスホテル", 'param' => 621],
            // ['genre_id' => 8, 'title' => "バス・観光バス", 'param' => 610],
            // ['genre_id' => 8, 'title' => "レンタカー", 'param' => 635],
            // ['genre_id' => 8, 'title' => "観光・観光案内", 'param' => 49],
            // ['genre_id' => 8, 'title' => "旅行・チケット販売", 'param' => 47],
            // ['genre_id' => 8, 'title' => "道の駅", 'param' => 53],
            // ['genre_id' => 8, 'title' => "銭湯・サウナ", 'param' => 665],
            // ['genre_id' => 8, 'title' => "温泉", 'param' => 49],
            // ['genre_id' => 8, 'title' => "観光・温泉・銭湯", 'param' => 49],
            // ['genre_id' => 8, 'title' => "キャンプ", 'param' => 51],
            // ['genre_id' => 8, 'title' => "果物・果樹園", 'param' => 605],
            // ['genre_id' => 8, 'title' => "公共宿泊施設", 'param' => 52],
            // ['genre_id' => 8, 'title' => "宿泊施設・宿泊所", 'param' => 57],
            // ['genre_id' => 8, 'title' => "ペンション", 'param' => 673],
            // ['genre_id' => 8, 'title' => "牧場", 'param' => 9541],
            // ['genre_id' => 8, 'title' => "ホテル・旅館予約", 'param' => 54],
            // ['genre_id' => 8, 'title' => "モーテル・ラブホテル", 'param' => 56],


            // ['genre_id' => 13, 'title' => "スポーツ施設", 'param' => 176],
            // ['genre_id' => 13, 'title' => "プレイスポット", 'param' => 174],
            // ['genre_id' => 13, 'title' => "アウトドア", 'param' => 181],
            // ['genre_id' => 13, 'title' => "フィットネス", 'param' => 183],
            // ['genre_id' => 13, 'title' => "屋内遊戯", 'param' => 177],
            // ['genre_id' => 13, 'title' => "釣り", 'param' => 192],
            // ['genre_id' => 13, 'title' => "博物館・美術館", 'param' => 178],
            // ['genre_id' => 13, 'title' => "ウィンタースポーツ", 'param' => 190],
            // ['genre_id' => 13, 'title' => "映画・劇場", 'param' => 173],
            // ['genre_id' => 13, 'title' => "屋外遊戯", 'param' => 186],
            // ['genre_id' => 13, 'title' => "公営競技", 'param' => 185],
            // ['genre_id' => 13, 'title' => "娯楽・漫才・寄席", 'param' => 5787],
            // ['genre_id' => 13, 'title' => "ゴルフ", 'param' => 175],
            // ['genre_id' => 13, 'title' => "ゴルフ場", 'param' => 1684],
            // ['genre_id' => 13, 'title' => "ゴルフ練習場", 'param' => 1685],
            // ['genre_id' => 13, 'title' => "サッカー", 'param' => 188],
            // ['genre_id' => 13, 'title' => "テニス", 'param' => 184],
            // ['genre_id' => 13, 'title' => "動物園・植物園・水族館", 'param' => 4247],
            // ['genre_id' => 13, 'title' => "ホール・会館", 'param' => 2855],
            // ['genre_id' => 13, 'title' => "マンガ・ネットカフェ", 'param' => 182],
            // ['genre_id' => 13, 'title' => "モータースポーツ", 'param' => 179],

            // ['genre_id' => 15, 'title' => "車検・整備・修理", 'param' => 128],
            // ['genre_id' => 15, 'title' => "自動車販売・管理", 'param' => 125],
            // ['genre_id' => 15, 'title' => "タイヤ・カー用品", 'param' => 131],
            // ['genre_id' => 15, 'title' => "ガソリンスタンド", 'param' => 135],
            // ['genre_id' => 15, 'title' => "中古車・買取", 'param' => 132],
            // ['genre_id' => 15, 'title' => "バイク販売・用品", 'param' => 127],
            // ['genre_id' => 15, 'title' => "洗車・コーティング", 'param' => 130],
            // ['genre_id' => 15, 'title' => "駐車場・パーキング", 'param' => 136],
            // ['genre_id' => 15, 'title' => "自動車解体", 'param' => 1225],
            // ['genre_id' => 15, 'title' => "バイク中古・買取", 'param' => 134],
            // ['genre_id' => 15, 'title' => "フロントガラス", 'param' => 1900393],
            // ['genre_id' => 15, 'title' => "レッカー・ロードサービス", 'param' => 1242],

            // ['genre_id' => 11, 'title' => "楽器購入・買取", 'param' => 1406],
            // ['genre_id' => 11, 'title' => "骨とう・古物", 'param' => 145],
            // ['genre_id' => 11, 'title' => "模型(プラモ)・ラジコン", 'param' => 152],
            // ['genre_id' => 11, 'title' => "画家・陶芸家・工芸家", 'param' => 3656],
            // ['genre_id' => 11, 'title' => "楽器修理・調律", 'param' => 144],
            // ['genre_id' => 11, 'title' => "ミシン・編機", 'param' => 1900342],
            // ['genre_id' => 11, 'title' => "囲碁・将棋・ボード", 'param' => 151],
            // ['genre_id' => 11, 'title' => "音楽家", 'param' => 3695],
            // ['genre_id' => 11, 'title' => "音楽制作・スタジオ", 'param' => 5872],
            // ['genre_id' => 11, 'title' => "額縁・額装", 'param' => 1341],
            // ['genre_id' => 11, 'title' => "キャラクタ", 'param' => 1900333],
            // ['genre_id' => 11, 'title' => "ギャラリー・画廊", 'param' => 1467],
            // ['genre_id' => 11, 'title' => "裁縫・手芸", 'param' => 146],
            // ['genre_id' => 11, 'title' => "材料", 'param' => 1900337],
            // ['genre_id' => 11, 'title' => "たばこ・喫煙", 'param' => 147],
            // ['genre_id' => 11, 'title' => "美術・陶芸・工芸品", 'param' => 148],
            // ['genre_id' => 11, 'title' => "古本・貸本", 'param' => 1158],
            // ['genre_id' => 11, 'title' => "望遠鏡・天文", 'param' => 5192],
            // ['genre_id' => 11, 'title' => "ホームクラフト", 'param' => 156],
            // ['genre_id' => 11, 'title' => "ライター・評論家", 'param' => 3618],


            // ['genre_id' => 14,'title' =>  "葬儀", 'param' => 139],
            // ['genre_id' => 14,'title' =>  "宗教", 'param' => 138],
            // ['genre_id' => 14,'title' =>  "写真・ビデオ・スライド", 'param' => 142],
            // ['genre_id' => 14,'title' =>  "仏壇・仏具・神具", 'param' => 140],
            // ['genre_id' => 14,'title' =>  "結婚・宴会", 'param' => 141],


            // ['genre_id' => 10,'title' =>  "幼稚園・保育施設", 'param' => 167],
            // ['genre_id' => 10,'title' =>  "楽器・音楽教室", 'param' => 158],
            // ['genre_id' => 10,'title' =>  "スポーツクラブ・教室", 'param' => 162],
            // ['genre_id' => 10,'title' =>  "各種学校", 'param' => 168],
            // ['genre_id' => 10,'title' =>  "カルチャースクール", 'param' => 1665],
            // ['genre_id' => 10,'title' =>  "バレエ・ダンス教室", 'param' => 1667],
            // ['genre_id' => 10,'title' =>  "塾・予備校", 'param' => 161],
            // ['genre_id' => 10,'title' =>  "語学・会話・スクール", 'param' => 170],
            // ['genre_id' => 10,'title' =>  "美術・工芸教室", 'param' => 4504],
            // ['genre_id' => 10,'title' =>  "求人・就職・派遣", 'param' => 169],
            // ['genre_id' => 10,'title' =>  "華道・茶道", 'param' => 163],
            // ['genre_id' => 10,'title' =>  "資格", 'param' => 160],
            // ['genre_id' => 10,'title' =>  "小・中・高・大学等", 'param' => 159],
            // ['genre_id' => 10,'title' =>  "書道・そろばん", 'param' => 172],
            // ['genre_id' => 10,'title' =>  "スポーツ関連クラブ", 'param' => 4331],
            // ['genre_id' => 10,'title' =>  "専修学校", 'param' => 164],
            // ['genre_id' => 10,'title' =>  "特殊教育諸学校", 'param' => 165],
            // ['genre_id' => 10,'title' =>  "トレーニング", 'param' => 1900308],
            // ['genre_id' => 10,'title' =>  "武道・格闘技", 'param' => 4480],
            // ['genre_id' => 10,'title' =>  "マリンスポーツ", 'param' => 4441],
            // ['genre_id' => 10,'title' =>  "幼児教室", 'param' => 166],
            // ['genre_id' => 10,'title' =>  "ヨガ・エクササイズ", 'param' => 1787],
            // ['genre_id' => 10,'title' =>  "料理教室", 'param' => 1669],

            // ['genre_id' => 12,'title' =>  "市区役所・町村役場", 'param' => 1834],
            // ['genre_id' => 12,'title' =>  "市区町村機関", 'param' => 202],
            // ['genre_id' => 12,'title' =>  "組合・団体", 'param' => 201],
            // ['genre_id' => 12,'title' =>  "消防・警察", 'param' => 203],
            // ['genre_id' => 12,'title' =>  "公民館・集会場", 'param' => 1880],
            // ['genre_id' => 12,'title' =>  "図書館", 'param' => 208],
            // ['genre_id' => 12,'title' =>  "都道府県庁・機関", 'param' => 206],
            // ['genre_id' => 12,'title' =>  "外国公館", 'param' => 5777],
            // ['genre_id' => 12,'title' =>  "官公署", 'param' => 204],
            // ['genre_id' => 12,'title' =>  "公庫・公社・事業団", 'param' => 209],
            // ['genre_id' => 12,'title' =>  "裁判所", 'param' => 205],


        ]);

    }
}